### ISSUE TITLE
resource.h:215:2: error: unknown type name 'uint64_t'

### ISSUE THREAD

**Issue by ymangu163** [discoteq/flock#30] opened 2020-08-06 07:37 UTC
resource.h:215:2: error: unknown type name 'uint64_t'

**Comment by josephholsten** [comment] 2020-08-06 21:17
I'm sorry, this project doesn't have a file named `resource.h`, doesn't actually use `uint64_t`. If it did, I'm not sure I could help because that's been part of `stdint.h` since C99. I'm closing this, but feel free to reopen if you have more reproduction steps!

**Closed by josephholsten** 2020-08-06 21:17 UTC
